unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

set -g mouse on
setw -g mode-keys vi
set -s set-clipboard on
set -g allow-passthrough on
set -s extended-keys on
# xterm-256color is used by many emulators that do not implement xterm
# extended keys consistently, which can break copy mode in VM guest terminals.
set -as terminal-features ",screen-256color:clipboard,tmux-256color:clipboard:extkeys,wezterm:clipboard:extkeys"
set -ga update-environment WEZTERM_APPEARANCE

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

unbind -T prefix Left
unbind -T prefix Down
unbind -T prefix Up
unbind -T prefix Right

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
