unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

set -g mouse on
set -s set-clipboard on
set -g allow-passthrough on
set -s extended-keys on
set -as terminal-features ",xterm-256color:clipboard:extkeys,screen-256color:clipboard,tmux-256color:clipboard:extkeys,wezterm:clipboard:extkeys"

bind - split-window -v -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"

unbind -T prefix Left
unbind -T prefix Down
unbind -T prefix Up
unbind -T prefix Right

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
