return {
	"Civitasv/cmake-tools.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"mfussenegger/nvim-dap",
	},
	ft = { "cmake" },
	cmd = {
		"CMakeBuild",
		"CMakeBuildCurrentFile",
		"CMakeClean",
		"CMakeCloseExecutor",
		"CMakeCloseRunner",
		"CMakeDebug",
		"CMakeDebugCurrentFile",
		"CMakeGenerate",
		"CMakeInstall",
		"CMakeLaunchArgs",
		"CMakeOpenCache",
		"CMakeOpenExecutor",
		"CMakeOpenRunner",
		"CMakeQuickBuild",
		"CMakeQuickDebug",
		"CMakeQuickRun",
		"CMakeQuickStart",
		"CMakeRun",
		"CMakeRunCurrentFile",
		"CMakeRunTest",
		"CMakeSelectBuildDir",
		"CMakeSelectBuildPreset",
		"CMakeSelectBuildTarget",
		"CMakeSelectBuildType",
		"CMakeSelectConfigurePreset",
		"CMakeSelectCwd",
		"CMakeSelectKit",
		"CMakeSelectLaunchTarget",
		"CMakeSelectTestPreset",
		"CMakeSettings",
		"CMakeShowTargetFiles",
		"CMakeStopExecutor",
		"CMakeStopRunner",
		"CMakeTargetSettings",
	},
	keys = {
		{ "<leader>mg", "<cmd>CMakeGenerate<CR>", desc = "CMake configure/generate" },
		{ "<leader>mb", "<cmd>CMakeBuild<CR>", desc = "CMake build" },
		{ "<leader>mf", "<cmd>CMakeBuildCurrentFile<CR>", desc = "CMake build current file" },
		{ "<leader>mr", "<cmd>CMakeRun<CR>", desc = "CMake run target" },
		{ "<leader>md", "<cmd>CMakeDebug<CR>", desc = "CMake debug target" },
		{ "<leader>mB", "<cmd>CMakeSelectBuildTarget<CR>", desc = "Select CMake build target" },
		{ "<leader>mL", "<cmd>CMakeSelectLaunchTarget<CR>", desc = "Select CMake launch target" },
		{ "<leader>mP", "<cmd>CMakeSelectConfigurePreset<CR>", desc = "Select CMake configure preset" },
		{ "<leader>mw", "<cmd>CMakeSelectCwd<CR>", desc = "Select CMake project directory" },
		{ "<leader>mo", "<cmd>CMakeOpenExecutor<CR>", desc = "Open CMake output" },
		{ "<leader>ms", "<cmd>CMakeSettings<CR>", desc = "Open CMake settings" },
		{ "<leader>mc", "<cmd>CMakeClean<CR>", desc = "Clean CMake build" },
	},
	opts = {
		cmake_generate_options = { "-DCMAKE_EXPORT_COMPILE_COMMANDS=1" },
		cmake_compile_commands_options = {
			action = "soft_link",
			target = vim.uv.cwd,
		},
		cmake_dap_configuration = {
			name = "CMake target",
			type = "codelldb",
			request = "launch",
			stopOnEntry = false,
			terminal = "integrated",
		},
		cmake_executor = {
			name = "quickfix",
			opts = {
				show = "only_on_error",
			},
		},
		cmake_runner = {
			name = "terminal",
			opts = {
				focus = true,
				start_insert = true,
			},
		},
	},
}
